name: FactionsPro
author: Tethered_ & iChaoticSoldier
description: Simple and Easy as Possible Ported From Bukkit(PC-Software) To Pocketmine-MP(PE-Software)
version: 1.7.9
main: Factions\FactionMain
api: [1.12.0, 3.0.0-ALPHA3]
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow Players Of use Faction Commands/SubCommands"
